#include "include.h"
#include "kbox.h"


const effect_info_cfg_t effect_info[CFG_MAX] = {
	[CFG_MIX_DRC]  = {"CFG_MIX_DRC#", BUF_OFS_CFG_MIX_DRC,   BUF_LEN_OFS_CFG_MIX_DRC},
	[CFG_MAGIC]    = {"CFG_MAGIC###", BUF_OFS_CFG_MAGIC,     BUF_LEN_OFS_CFG_MAGIC},
	[CFG_ECHO]     = {"CFG_ECHO####", BUF_OFS_CFG_ECHO,      BUF_LEN_OFS_CFG_ECHO},
	[CFG_HOWL]     = {"CFG_HOWL####", BUF_OFS_CFG_HOWL,      BUF_LEN_OFS_CFG_HOWL},
	[CFG_LOCEQ]    = {"CFG_LOCEQ###", BUF_OFS_CFG_LOCEQ,     BUF_LEN_OFS_CFG_LOCEQ},
	[CFG_LOCDRC]   = {"CFG_LOCDRC##", BUF_OFS_CFG_LOCDRC,    BUF_LEN_OFS_CFG_LOCDRC},
	[CFG_DAC_EQ]   = {"CFG_DAC_EQ##", BUF_OFS_CFG_DAC_EQ,    BUF_LEN_OFS_CFG_DAC_EQ},
	[CFG_DAC_DRC]  = {"CFG_DAC_DRC#", BUF_OFS_CFG_DAC_DRC,   BUF_LEN_OFS_CFG_DAC_DRC},
	[CFG_PRE_EQ]   = {"CFG_PRE_EQ##", BUF_OFS_CFG_PRE_EQ,    BUF_LEN_OFS_CFG_PRE_EQ},
	[CFG_DY_EQ]    = {"CFG_DY_EQ###", BUF_OFS_CFG_DY_EQ,     BUF_LEN_OFS_CFG_DY_EQ},
	[CFG_MULT_DRC] = {"CFG_MULT_DRC", BUF_OFS_CFG_MULT_DRC,  BUF_LEN_OFS_CFG_MULT_DRC},
	[CFG_ALL_EQ]   = {"CFG_ALL_EQ##", BUF_OFS_CFG_ALL_EQ,    BUF_LEN_OFS_CFG_ALL_EQ},
	[CFG_ALL_DRC]  = {"CFG_ALL_DRC#", BUF_OFS_CFG_ALL_DRC,   BUF_LEN_OFS_CFG_ALL_DRC},
	[CFG_MSBC_EQ]  = {"CFG_MSBC_EQ#", BUF_OFS_CFG_MSBC_EQ,   BUF_LEN_OFS_CFG_MSBC_EQ},
	[CFG_MSBC_DRC] = {"CFG_MSBC_DRC", BUF_OFS_CFG_MSBC_DRC,  BUF_LEN_OFS_CFG_MSBC_DRC},
	[CFG_CSVD_EQ]  = {"CFG_CSVD_EQ#", BUF_OFS_CFG_CSVD_EQ,   BUF_LEN_OFS_CFG_CSVD_EQ},
	[CFG_CSVD_DRC] = {"CFG_CSVD_DRC", BUF_OFS_CFG_CSVD_DRC,  BUF_LEN_OFS_CFG_CSVD_DRC},
	[CFG_COUNTEQ]  = {"CFG_COUNTEQ#", BUF_OFS_CFG_COUNTEQ,   BUF_LEN_OFS_CFG_COUNTEQ},
	[CFG_CLAS_EQ]  = {"CFG_CLAS_EQ#", BUF_OFS_CFG_CLAS_EQ,   BUF_LEN_OFS_CFG_CLAS_EQ},
	[CFG_POP_EQ]   = {"CFG_POP_EQ##", BUF_OFS_CFG_POP_EQ,    BUF_LEN_OFS_CFG_POP_EQ},
	[CFG_ROCK_EQ]  = {"CFG_ROCK_EQ#", BUF_OFS_CFG_ROCK_EQ,   BUF_LEN_OFS_CFG_ROCK_EQ},
	[CFG_JAZZ_EQ]  = {"CFG_JAZZ_EQ#", BUF_OFS_CFG_JAZZ_EQ,   BUF_LEN_OFS_CFG_JAZZ_EQ},
	[CFG_MIX_EQ]   = {"CFG_MIX_EQ##", BUF_OFS_CFG_MIX_EQ,    BUF_LEN_OFS_CFG_MIX_EQ},
};


/*模块初始化更新回调注册表 cv到应用层使用
const effect_update_callback_t effect_update_callback_tbl[CFG_MAX] = {
	[CFG_MIX_DRC]  = {NULL},
	[CFG_MAGIC]    = {NULL},
	[CFG_ECHO]     = {NULL},
	[CFG_HOWL]     = {NULL},
	[CFG_LOCEQ]    = {NULL},
	[CFG_LOCDRC]   = {NULL},
	[CFG_DAC_EQ]   = {NULL},
	[CFG_DAC_DRC]  = {NULL},
	[CFG_PRE_EQ]   = {NULL},
	[CFG_DY_EQ]    = {NULL},
	[CFG_MULT_DRC] = {NULL},
	[CFG_ALL_EQ]   = {NULL},
	[CFG_ALL_DRC]  = {NULL},
	[CFG_MSBC_EQ]  = {NULL},
	[CFG_MSBC_DRC] = {NULL},
	[CFG_CSVD_EQ]  = {NULL},
	[CFG_CSVD_DRC] = {NULL},
	[CFG_COUNTEQ]  = {NULL},
	[CFG_CLAS_EQ]  = {NULL},
	[CFG_POP_EQ]   = {NULL},
	[CFG_ROCK_EQ]  = {NULL},
	[CFG_JAZZ_EQ]  = {NULL},
	[CFG_MIX_EQ]   = {NULL},
};
*/