
#ifndef _KYLIN_SFR_
#define _KYLIN_SFR_


#ifndef __ASSEMBLER__
#define SFR_RO *(volatile unsigned long const *)
#define SFR_WO *(volatile unsigned long*)
#define SFR_RW *(volatile unsigned long*)
#define SWINT()      asm(".long 0xb0030057")
#define EEBREAKINT() asm(".long 0xb0040057")
#else
#define SFR_RO
#define SFR_WO
#define SFR_RW
#define SWINT      .long 0xb0030057
#define EEBREAKINT .long 0xb0040057
#endif

#define SFR_BASE   0x00000100    // address 0~255 is reserved
#define SFR0_BASE  (SFR_BASE + 0x0000)
#define SFR1_BASE  (SFR_BASE + 0x0100)
#define SFR2_BASE  (SFR_BASE + 0x0200)
#define SFR3_BASE  (SFR_BASE + 0x0300)
#define SFR4_BASE  (SFR_BASE + 0x0400)
#define SFR5_BASE  (SFR_BASE + 0x0500)
#define SFR6_BASE  (SFR_BASE + 0x0600)
#define SFR7_BASE  (SFR_BASE + 0x0700)
#define SFR8_BASE  (SFR_BASE + 0x0800)
#define SFR9_BASE  (SFR_BASE + 0x0900)
#define SFR10_BASE (SFR_BASE + 0x0a00)
#define SFR11_BASE (SFR_BASE + 0x0b00)
#define SFR12_BASE (SFR_BASE + 0x0c00)
#define SFR13_BASE (SFR_BASE + 0x0d00)
#define SFR14_BASE (SFR_BASE + 0x0e00)
#define SFR15_BASE (SFR_BASE + 0x0f00)
#define SFR16_BASE (SFR_BASE + 0x1000)
#define SFR17_BASE (SFR_BASE + 0x1100)
#define SFR30_BASE (SFR_BASE + 0x1e00)

//------------------------- SFR Group0 ---------------------------------------//
#define TMR0CON              SFR_RW (SFR0_BASE + 0x00*4)
#define TMR0CPND             SFR_RW (SFR0_BASE + 0x01*4)
#define TMR0CNT              SFR_RW (SFR0_BASE + 0x02*4)
#define TMR0PR               SFR_RW (SFR0_BASE + 0x03*4)
#define TMR1CON              SFR_RW (SFR0_BASE + 0x04*4)
#define TMR1CPND             SFR_RW (SFR0_BASE + 0x05*4)
#define TMR1CNT              SFR_RW (SFR0_BASE + 0x06*4)
#define TMR1PR               SFR_RW (SFR0_BASE + 0x07*4)
#define TMR2CON              SFR_RW (SFR0_BASE + 0x08*4)
#define TMR2CPND             SFR_RW (SFR0_BASE + 0x09*4)
#define TMR2CNT              SFR_RW (SFR0_BASE + 0x0a*4)
#define TMR2PR               SFR_RW (SFR0_BASE + 0x0b*4)
#define TMR3CON              SFR_RW (SFR0_BASE + 0x0c*4)
#define TMR3CPND             SFR_RW (SFR0_BASE + 0x0d*4)
#define TMR3CNT              SFR_RW (SFR0_BASE + 0x0e*4)
#define TMR3PR               SFR_RW (SFR0_BASE + 0x0f*4)
#define TMR3CPT              SFR_RW (SFR0_BASE + 0x10*4)
#define TMR3DUTY0            SFR_RW (SFR0_BASE + 0x11*4)
#define TMR3DUTY1            SFR_RW (SFR0_BASE + 0x12*4)
#define TMR3DUTY2            SFR_RW (SFR0_BASE + 0x13*4)
#define TMR4CON              SFR_RW (SFR0_BASE + 0x14*4)
#define TMR4CPND             SFR_RW (SFR0_BASE + 0x15*4)
#define TMR4CNT              SFR_RW (SFR0_BASE + 0x16*4)
#define TMR4PR               SFR_RW (SFR0_BASE + 0x17*4)
#define TMR4CPT              SFR_RW (SFR0_BASE + 0x18*4)
#define TMR4DUTY0            SFR_RW (SFR0_BASE + 0x19*4)
#define TMR4DUTY1            SFR_RW (SFR0_BASE + 0x1a*4)
#define TMR4DUTY2            SFR_RW (SFR0_BASE + 0x1b*4)
#define TMR5CON              SFR_RW (SFR0_BASE + 0x1c*4)
#define TMR5CPND             SFR_RW (SFR0_BASE + 0x1d*4)
#define TMR5CNT              SFR_RW (SFR0_BASE + 0x1e*4)
#define TMR5PR               SFR_RW (SFR0_BASE + 0x1f*4)
#define TMR5CPT              SFR_RW (SFR0_BASE + 0x20*4)
#define TMR5DUTY0            SFR_RW (SFR0_BASE + 0x21*4)
#define TMR5DUTY1            SFR_RW (SFR0_BASE + 0x22*4)
#define TMR5DUTY2            SFR_RW (SFR0_BASE + 0x23*4)
#define TMR5DUTY3            SFR_RW (SFR0_BASE + 0x24*4)
#define TMR5DUTY4            SFR_RW (SFR0_BASE + 0x25*4)
#define TMR5DUTY5            SFR_RW (SFR0_BASE + 0x26*4)
#define UART0CON             SFR_RW (SFR0_BASE + 0x27*4)
#define UART0CPND            SFR_RW (SFR0_BASE + 0x28*4)
#define UART0BAUD            SFR_RW (SFR0_BASE + 0x29*4)
#define UART0DATA            SFR_RW (SFR0_BASE + 0x2a*4)
#define UART1CON             SFR_RW (SFR0_BASE + 0x2b*4)
#define UART1CPND            SFR_RW (SFR0_BASE + 0x2c*4)
#define UART1BAUD            SFR_RW (SFR0_BASE + 0x2d*4)
#define UART1DATA            SFR_RW (SFR0_BASE + 0x2e*4)
#define UART2CON             SFR_RW (SFR0_BASE + 0x2f*4)
#define UART2CPND            SFR_RW (SFR0_BASE + 0x30*4)
#define UART2BAUD            SFR_RW (SFR0_BASE + 0x31*4)
#define UART2DATA            SFR_RW (SFR0_BASE + 0x32*4)
#define HSUT0CON             SFR_RW (SFR0_BASE + 0x33*4)
#define HSUT0CPND            SFR_RW (SFR0_BASE + 0x34*4)
#define HSUT0BAUD            SFR_RW (SFR0_BASE + 0x35*4)
#define HSUT0DATA            SFR_RW (SFR0_BASE + 0x36*4)
#define HSUT0TXCNT           SFR_RW (SFR0_BASE + 0x37*4)
#define HSUT0TXADR           SFR_RW (SFR0_BASE + 0x38*4)
#define HSUT0RXCNT           SFR_RW (SFR0_BASE + 0x39*4)
#define HSUT0RXADR           SFR_RW (SFR0_BASE + 0x3a*4)
#define HSUT0FIFOCNT         SFR_RW (SFR0_BASE + 0x3b*4)
#define HSUT0FIFO            SFR_RW (SFR0_BASE + 0x3c*4)
#define HSUT0FIFOADR         SFR_RW (SFR0_BASE + 0x3d*4)
#define HSUT0TMRCNT          SFR_RW (SFR0_BASE + 0x3e*4)
#define HSUT0FCCON           SFR_RW (SFR0_BASE + 0x3f*4)

//------------------------- SFR Group1 ---------------------------------------//
#define WDTCON               SFR_RW (SFR1_BASE + 0x00*4)
#define RTCCON               SFR_RW (SFR1_BASE + 0x01*4)
#define RTCCPND              SFR_RW (SFR1_BASE + 0x02*4)
#define VBRSTCON             SFR_RW (SFR1_BASE + 0x03*4)
#define PWRCON0              SFR_RW (SFR1_BASE + 0x04*4)
#define PWRCON1              SFR_RW (SFR1_BASE + 0x05*4)
#define PWRCON2              SFR_RW (SFR1_BASE + 0x06*4)
#define PWRCON3              SFR_RW (SFR1_BASE + 0x07*4)
#define LPMCON               SFR_RW (SFR1_BASE + 0x08*4)
#define LVDCON               SFR_RW (SFR1_BASE + 0x09*4)
#define RSTCON0              SFR_RW (SFR1_BASE + 0x0a*4)
#define CRSTPND              SFR_RW (SFR1_BASE + 0x0b*4)
//efine                      SFR_RW (SFR1_BASE + 0x0c*4)
//efine                      SFR_RW (SFR1_BASE + 0x0d*4)
//efine                      SFR_RW (SFR1_BASE + 0x0e*4)
//efine                      SFR_RW (SFR1_BASE + 0x0f*4)
//efine                      SFR_RW (SFR1_BASE + 0x10*4)
//efine                      SFR_RW (SFR1_BASE + 0x11*4)
//#define XOSCCON1             SFR_RW (SFR1_BASE + 0x12*4)
#define XOSCCON              SFR_RW (SFR1_BASE + 0x13*4)
#define CLKCON0              SFR_RW (SFR1_BASE + 0x14*4)
#define CLKCON1              SFR_RW (SFR1_BASE + 0x15*4)
#define CLKCON2              SFR_RW (SFR1_BASE + 0x16*4)
#define CLKCON3              SFR_RW (SFR1_BASE + 0x17*4)
#define CLKCON4              SFR_RW (SFR1_BASE + 0x18*4)
#define CLKCON5              SFR_RW (SFR1_BASE + 0x19*4)
#define CLKGAT0              SFR_RW (SFR1_BASE + 0x1a*4)
#define CLKGAT1              SFR_RW (SFR1_BASE + 0x1b*4)
#define CLKGAT2              SFR_RW (SFR1_BASE + 0x1c*4)
#define CLKGAT3              SFR_RW (SFR1_BASE + 0x1d*4)
#define CLKGAT4              SFR_RW (SFR1_BASE + 0x1e*4)
#define CLKGAT5              SFR_RW (SFR1_BASE + 0x1f*4)
#define CLKDIVCON0           SFR_RW (SFR1_BASE + 0x20*4)
#define CLKDIVCON1           SFR_RW (SFR1_BASE + 0x21*4)
#define CLKDIVCON2           SFR_RW (SFR1_BASE + 0x22*4)
#define CLKDIVCON3           SFR_RW (SFR1_BASE + 0x23*4)
#define CLKDIVCON4           SFR_RW (SFR1_BASE + 0x24*4)
#define CLKDIVCON5           SFR_RW (SFR1_BASE + 0x25*4)
//efine                      SFR_RW (SFR1_BASE + 0x26*4)
//efine                      SFR_RW (SFR1_BASE + 0x27*4)
#define MEMCON0              SFR_RW (SFR1_BASE + 0x28*4)
#define MEMCON1              SFR_RW (SFR1_BASE + 0x29*4)
#define MEMCON2              SFR_RW (SFR1_BASE + 0x2a*4)
#define MEMCON3              SFR_RW (SFR1_BASE + 0x2b*4)
#define MEMCON4              SFR_RW (SFR1_BASE + 0x2c*4)
#define PRCLKCON0            SFR_RW (SFR1_BASE + 0x2d*4)
#define PRCLKDIVCON0         SFR_RW (SFR1_BASE + 0x2e*4)
#define PRCLKDIVCON1         SFR_RW (SFR1_BASE + 0x2f*4)
#define PLL0CON0             SFR_RW (SFR1_BASE + 0x30*4)
#define PLL0CON1             SFR_RW (SFR1_BASE + 0x31*4)
#define PLL0CON2             SFR_RW (SFR1_BASE + 0x32*4)
#define PLL0DIV              SFR_RW (SFR1_BASE + 0x33*4)
//#define PLL1CON1             SFR_RW (SFR1_BASE + 0x34*4)
//#define PLL1DIV              SFR_RW (SFR1_BASE + 0x35*4)
//#define PLL2CON0             SFR_RW (SFR1_BASE + 0x36*4)
//#define PLL2CON1             SFR_RW (SFR1_BASE + 0x37*4)
//#define PLL2DIV              SFR_RW (SFR1_BASE + 0x38*4)
//efine                      SFR_RW (SFR1_BASE + 0x39*4)
#define DBGCON1              SFR_RW (SFR1_BASE + 0x3a*4)
#define DBGCON               SFR_RW (SFR1_BASE + 0x3b*4)
#define CPDATA               SFR_RW (SFR1_BASE + 0x3c*4)
#define SPMODE               SFR_RW (SFR1_BASE + 0x3d*4)
#define DEVICEID             SFR_RW (SFR1_BASE + 0x3e*4)
#define VERSIONID            SFR_RW (SFR1_BASE + 0x3f*4)

//------------------------- SFR Group2 ---------------------------------------//
#define BTCON2               SFR_RW (SFR2_BASE + 0x00*4)
#define BTCON3               SFR_RW (SFR2_BASE + 0x01*4)
#define BTCON4               SFR_RW (SFR2_BASE + 0x02*4)
#define BTDMAADR             SFR_RW (SFR2_BASE + 0x03*4)
#define BTRFDMACON           SFR_RW (SFR2_BASE + 0x04*4)
#define BTADDMACNT           SFR_RW (SFR2_BASE + 0x05*4)
#define BTADDMAADR           SFR_RW (SFR2_BASE + 0x06*4)
#define BTDADMACNT           SFR_RW (SFR2_BASE + 0x07*4)
#define BTDADMAADR           SFR_RW (SFR2_BASE + 0x08*4)
#define BTPHYTSCON           SFR_RW (SFR2_BASE + 0x09*4)
#define BTSNFCNT             SFR_RW (SFR2_BASE + 0x0a*4)
#define BTSNCLKN             SFR_RW (SFR2_BASE + 0x0b*4)
//efine                      SFR_RW (SFR2_BASE + 0x0c*4)
//efine                      SFR_RW (SFR2_BASE + 0x0d*4)
//efine                      SFR_RW (SFR2_BASE + 0x0e*4)
//efine                      SFR_RW (SFR2_BASE + 0x0f*4)
//#define  PORTINTEDG1         SFR_RW (SFR2_BASE + 0x10*4)
//#define  PORTINTEN1          SFR_RW (SFR2_BASE + 0x11*4)
//#define  PORTINTRISESRC1     SFR_RW (SFR2_BASE + 0x12*4)
//#define  PORTINTFALLSRC1     SFR_RW (SFR2_BASE + 0x13*4)
//#define  LPPORTINTEDG1       SFR_RW (SFR2_BASE + 0x14*4)
//#define  LPPORTINTEN1        SFR_RW (SFR2_BASE + 0x15*4)
//#define  LPPORTINTRISESRC1   SFR_RW (SFR2_BASE + 0x16*4)
//#define  LPPORTINTFALLSRC1   SFR_RW (SFR2_BASE + 0x17*4)
//efine                     SFR_RW (SFR2_BASE + 0x18*4)
//efine                     SFR_RW (SFR2_BASE + 0x19*4)
//efine                      SFR_RW (SFR2_BASE + 0x1a*4)
//efine                      SFR_RW (SFR2_BASE + 0x1b*4)
//efine                      SFR_RW (SFR2_BASE + 0x1c*4)
#define FUNCINCON            SFR_RW (SFR2_BASE + 0x1d*4)
#define FUNCOUTCON           SFR_RW (SFR2_BASE + 0x1e*4)
#define FUNCOUTMCON          SFR_RW (SFR2_BASE + 0x1f*4)
#define FUNCMCON0            SFR_RW (SFR2_BASE + 0x20*4)
#define FUNCMCON1            SFR_RW (SFR2_BASE + 0x21*4)
#define FUNCMCON2            SFR_RW (SFR2_BASE + 0x22*4)
#define FUNCMCON3            SFR_RW (SFR2_BASE + 0x23*4)
#define FUNCMCON4            SFR_RW (SFR2_BASE + 0x24*4)
#define FUNCMCON5            SFR_RW (SFR2_BASE + 0x25*4)
#define WKUPCON              SFR_RW (SFR2_BASE + 0x26*4)
#define WKUPEDG              SFR_RW (SFR2_BASE + 0x27*4)
#define WKUPIE               SFR_RW (SFR2_BASE + 0x28*4)
#define WKUPCPND             SFR_RW (SFR2_BASE + 0x29*4)
#define WKPINMAP             SFR_RW (SFR2_BASE + 0x2a*4)
#define PORTINTEDG           SFR_RW (SFR2_BASE + 0x2b*4)
#define PORTINTEN            SFR_RW (SFR2_BASE + 0x2c*4)
#define PORTINTRISESRC       SFR_RW (SFR2_BASE + 0x2d*4)
#define PORTINTFALLSRC       SFR_RW (SFR2_BASE + 0x2e*4)
//efine                      SFR_RW (SFR2_BASE + 0x2f*4)
#define LPWKUPCON            SFR_RW (SFR2_BASE + 0x30*4)
#define LPWKUPCPND           SFR_RW (SFR2_BASE + 0x31*4)
#define LPPORTINTEDG         SFR_RW (SFR2_BASE + 0x32*4)
#define LPPORTINTEN          SFR_RW (SFR2_BASE + 0x33*4)
#define LPPORTINTRISESRC     SFR_RW (SFR2_BASE + 0x34*4)
#define LPPORTINTFALLSRC     SFR_RW (SFR2_BASE + 0x35*4)
//#define                      SFR_RW (SFR2_BASE + 0x36*4)
//#define                      SFR_RW (SFR2_BASE + 0x37*4)
#define TICK0CON             SFR_RW (SFR2_BASE + 0x38*4)
#define TICK0CPND            SFR_RW (SFR2_BASE + 0x39*4)
#define TICK0CNT             SFR_RW (SFR2_BASE + 0x3a*4)
#define TICK0PR              SFR_RW (SFR2_BASE + 0x3b*4)
#define TICK1CON             SFR_RW (SFR2_BASE + 0x3c*4)
#define TICK1CPND            SFR_RW (SFR2_BASE + 0x3d*4)
#define TICK1CNT             SFR_RW (SFR2_BASE + 0x3e*4)
#define TICK1PR              SFR_RW (SFR2_BASE + 0x3f*4)

//------------------------- SFR Group3 ---------------------------------------//
#define USBCON0              SFR_RW (SFR3_BASE + 0x00*4)
#define USBCON1              SFR_RW (SFR3_BASE + 0x01*4)
#define USBCON2              SFR_RW (SFR3_BASE + 0x02*4)
#define USBCON3              SFR_RW (SFR3_BASE + 0x03*4)
#define USBCON4              SFR_RW (SFR3_BASE + 0x04*4)
#define USBEP0ADR            SFR_RW (SFR3_BASE + 0x05*4)
#define USBEP1RXADR          SFR_RW (SFR3_BASE + 0x06*4)
#define USBEP1TXADR          SFR_RW (SFR3_BASE + 0x07*4)
#define USBEP2RXADR          SFR_RW (SFR3_BASE + 0x08*4)
#define USBEP2TXADR          SFR_RW (SFR3_BASE + 0x09*4)
#define USBEP3RXADR          SFR_RW (SFR3_BASE + 0x0a*4)
#define USBEP3TXADR          SFR_RW (SFR3_BASE + 0x0b*4)
#define USBEP4RXADR          SFR_RW (SFR3_BASE + 0x0c*4)
#define USBEP4TXADR          SFR_RW (SFR3_BASE + 0x0d*4)
#define USBEP5RXADR          SFR_RW (SFR3_BASE + 0x0e*4)
#define USBEP5TXADR          SFR_RW (SFR3_BASE + 0x0f*4)
#define USBEP6RXADR          SFR_RW (SFR3_BASE + 0x10*4)
#define USBEP6TXADR          SFR_RW (SFR3_BASE + 0x11*4)
//efine                      SFR_RW (SFR3_BASE + 0x12*4)
#define SPI0DMALEFT          SFR_RW (SFR3_BASE + 0x13*4)
#define SPI1DMALEFT          SFR_RW (SFR3_BASE + 0x14*4)
//efine                      SFR_RW (SFR3_BASE + 0x15*4)
#define SD0CON               SFR_RW (SFR3_BASE + 0x16*4)
#define SD0CPND              SFR_RW (SFR3_BASE + 0x17*4)
#define SD0BAUD              SFR_RW (SFR3_BASE + 0x18*4)
#define SD0CMD               SFR_RW (SFR3_BASE + 0x19*4)
#define SD0ARG3              SFR_RW (SFR3_BASE + 0x1a*4)
#define SD0ARG2              SFR_RW (SFR3_BASE + 0x1b*4)
#define SD0ARG1              SFR_RW (SFR3_BASE + 0x1c*4)
#define SD0ARG0              SFR_RW (SFR3_BASE + 0x1d*4)
#define SD0DMAADR            SFR_RW (SFR3_BASE + 0x1e*4)
#define SD0DMACNT            SFR_RW (SFR3_BASE + 0x1f*4)
#define SPI0CON              SFR_RW (SFR3_BASE + 0x20*4)
#define SPI0BUF              SFR_RW (SFR3_BASE + 0x21*4)
#define SPI0BAUD             SFR_RW (SFR3_BASE + 0x22*4)
#define SPI0CPND             SFR_RW (SFR3_BASE + 0x23*4)
#define SPI0DMACNT           SFR_RW (SFR3_BASE + 0x24*4)
#define SPI0DMAADR           SFR_RW (SFR3_BASE + 0x25*4)
#define SPI1CON              SFR_RW (SFR3_BASE + 0x26*4)
#define SPI1BUF              SFR_RW (SFR3_BASE + 0x27*4)
#define SPI1BAUD             SFR_RW (SFR3_BASE + 0x28*4)
#define SPI1CPND             SFR_RW (SFR3_BASE + 0x29*4)
#define SPI1DMACNT           SFR_RW (SFR3_BASE + 0x2a*4)
#define SPI1DMAADR           SFR_RW (SFR3_BASE + 0x2b*4)
#define CRCDAT               SFR_RW (SFR3_BASE + 0x2c*4)
#define CRCRES               SFR_RW (SFR3_BASE + 0x2d*4)
#define LFSRRES              SFR_RW (SFR3_BASE + 0x2e*4)
#define LFCRCCON             SFR_RW (SFR3_BASE + 0x2f*4)
#define CRC1DAT              SFR_RW (SFR3_BASE + 0x30*4)
#define CRC1RES              SFR_RW (SFR3_BASE + 0x31*4)
//efine                      SFR_RW (SFR3_BASE + 0x32*4)
//efine                      SFR_RW (SFR3_BASE + 0x33*4)
//efine                      SFR_RW (SFR3_BASE + 0x34*4)
//efine                      SFR_RW (SFR3_BASE + 0x35*4)
//efine                      SFR_RW (SFR3_BASE + 0x36*4)
//efine                      SFR_RW (SFR3_BASE + 0x37*4)
#define WPTDAT               SFR_RW (SFR3_BASE + 0x38*4)
#define WPTERRSTA            WPTDAT
#define WPTCON               SFR_RW (SFR3_BASE + 0x39*4)
#define WPTPND               SFR_RW (SFR3_BASE + 0x3a*4)
#define WPTADR               SFR_RW (SFR3_BASE + 0x3b*4)
#define FREQDETCON           SFR_RW (SFR3_BASE + 0x3c*4)
#define FREQDETCPND          SFR_RW (SFR3_BASE + 0x3d*4)
#define FREQDETCNT           SFR_RW (SFR3_BASE + 0x3e*4)
#define FREQDETTGT           SFR_RW (SFR3_BASE + 0x3f*4)

//------------------------- SFR Group4 ---------------------------------------//
#define EXCEPTPND            SFR_RW (SFR4_BASE + 0x00*4)
#define EXCEPTCPND           SFR_RW (SFR4_BASE + 0x01*4)
#define NMICON               SFR_RW (SFR4_BASE + 0x02*4)
#define BP0ADR               SFR_RW (SFR4_BASE + 0x03*4)
#define BP1ADR               SFR_RW (SFR4_BASE + 0x04*4)
#define BP2ADR               SFR_RW (SFR4_BASE + 0x05*4)
#define BP3ADR               SFR_RW (SFR4_BASE + 0x06*4)
#define BP4ADR               SFR_RW (SFR4_BASE + 0x07*4)
#define BP5ADR               SFR_RW (SFR4_BASE + 0x08*4)
#define BP6ADR               SFR_RW (SFR4_BASE + 0x09*4)
//efine ICLOCK1              SFR_RW (SFR4_BASE + 0x0a*4)
//efine ICVAL1               SFR_RW (SFR4_BASE + 0x0b*4)
#define PICCONCLR            SFR_RW (SFR4_BASE + 0x0c*4)
#define PICCONSET            SFR_RW (SFR4_BASE + 0x0d*4)
#define PICENCLR             SFR_RW (SFR4_BASE + 0x0e*4)
#define PICENSET             SFR_RW (SFR4_BASE + 0x0f*4)
#define PICCON               SFR_RW (SFR4_BASE + 0x10*4)
#define PICEN                SFR_RW (SFR4_BASE + 0x11*4)
#define PICPR                SFR_RW (SFR4_BASE + 0x12*4)
#define PICADR               SFR_RW (SFR4_BASE + 0x13*4)
#define PICPND               SFR_RW (SFR4_BASE + 0x14*4)
#define CACHCON0             SFR_RW (SFR4_BASE + 0x15*4)
#define CACHCON1             SFR_RW (SFR4_BASE + 0x16*4)
#define ICTAG                SFR_RW (SFR4_BASE + 0x17*4)
#define ICINDEX              SFR_RW (SFR4_BASE + 0x18*4)
#define ICADRMS              SFR_RW (SFR4_BASE + 0x19*4)
#define ICLOCK               SFR_RW (SFR4_BASE + 0x1a*4)
#define ICVAL                SFR_RW (SFR4_BASE + 0x1b*4)
//efine                      SFR_RW (SFR4_BASE + 0x1c*4)
#define SWBK                 SFR_RW (SFR4_BASE + 0x1d*4)
#define EPICCON              SFR_RW (SFR4_BASE + 0x1e*4)
#define EPC                  SFR_RW (SFR4_BASE + 0x1f*4)
#define BP7ADR               SFR_RW (SFR4_BASE + 0x20*4)
//efine                      SFR_RW (SFR4_BASE + 0x21*4)
//efine                      SFR_RW (SFR4_BASE + 0x22*4)
//efine                      SFR_RW (SFR4_BASE + 0x23*4)
//efine                      SFR_RW (SFR4_BASE + 0x24*4)
//efine                      SFR_RW (SFR4_BASE + 0x25*4)
//efine                      SFR_RW (SFR4_BASE + 0x26*4)
//efine                      SFR_RW (SFR4_BASE + 0x27*4)
//efine                      SFR_RW (SFR4_BASE + 0x28*4)
#define PICPR1               SFR_RW (SFR4_BASE + 0x29*4)
//efine                      SFR_RW (SFR4_BASE + 0x2a*4)
//efine                      SFR_RW (SFR4_BASE + 0x2b*4)
//efine                      SFR_RW (SFR4_BASE + 0x2c*4)
//efine                      SFR_RW (SFR4_BASE + 0x2d*4)
#define PCERR                SFR_RW (SFR4_BASE + 0x2e*4)
#define PCST                 SFR_RW (SFR4_BASE + 0x2f*4)
//efine                      SFR_RW (SFR4_BASE + 0x30*4)
//efine                      SFR_RW (SFR4_BASE + 0x31*4)
//efine                      SFR_RW (SFR4_BASE + 0x32*4)
//efine                      SFR_RW (SFR4_BASE + 0x33*4)
//efine                      SFR_RW (SFR4_BASE + 0x34*4)
//efine                      SFR_RW (SFR4_BASE + 0x35*4)
//efine                      SFR_RW (SFR4_BASE + 0x36*4)
//efine                      SFR_RW (SFR4_BASE + 0x37*4)
//efine                      SFR_RW (SFR4_BASE + 0x38*4)
//efine                      SFR_RW (SFR4_BASE + 0x39*4)
//efine                      SFR_RW (SFR4_BASE + 0x3a*4)
//efine                      SFR_RW (SFR4_BASE + 0x3b*4)
//efine                      SFR_RW (SFR4_BASE + 0x3c*4)
//efine                      SFR_RW (SFR4_BASE + 0x3d*4)
//efine                      SFR_RW (SFR4_BASE + 0x3e*4)
#define CPUID                SFR_RW (SFR4_BASE + 0x3f*4)

//------------------------- SFR Group5 ---------------------------------------//
#define IISCON0              SFR_RW (SFR5_BASE + 0x00*4)
#define IISBAUD              SFR_RW (SFR5_BASE + 0x01*4)
#define IISDMACNT            SFR_RW (SFR5_BASE + 0x02*4)
#define IISDMAOADR0          SFR_RW (SFR5_BASE + 0x03*4)
#define IISDMAOADR1          SFR_RW (SFR5_BASE + 0x04*4)
#define IISDMAIADR0          SFR_RW (SFR5_BASE + 0x05*4)
#define IISDMAIADR1          SFR_RW (SFR5_BASE + 0x06*4)
#define IISCPND              SFR_RW (SFR5_BASE + 0x07*4)
//#define IICCON1              SFR_RW (SFR5_BASE + 0x08*4)
//#define IICCMDA              SFR_RW (SFR5_BASE + 0x09*4)
//#define IICDATA              SFR_RW (SFR5_BASE + 0x0a*4)
//#define IICDMAADR            SFR_RW (SFR5_BASE + 0x0b*4)
//#define IICDMACNT            SFR_RW (SFR5_BASE + 0x0c*4)
//#define IICSSTS              SFR_RW (SFR5_BASE + 0x0d*4)
#define LEDCCON             SFR_RW (SFR5_BASE + 0x0e*4)
#define LEDCFD              SFR_RW (SFR5_BASE + 0x0f*4)
#define LEDCLP              SFR_RW (SFR5_BASE + 0x10*4)
#define LEDCTIX             SFR_RW (SFR5_BASE + 0x11*4)
#define LEDCRSTX            SFR_RW (SFR5_BASE + 0x12*4)
#define LEDCADDR            SFR_RW (SFR5_BASE + 0x13*4)
#define LEDCCNT             SFR_RW (SFR5_BASE + 0x14*4)
#define LEDCPEND            SFR_RW (SFR5_BASE + 0x15*4)
//efine                      SFR_RW (SFR5_BASE + 0x16*4)
//#define CVSDCON0             SFR_RW (SFR5_BASE + 0x17*4)
//#define CVSDCPND             SFR_RW (SFR5_BASE + 0x18*4)
//#define CVSDDMACNT           SFR_RW (SFR5_BASE + 0x19*4)
//#define CVSDDMAERADR         SFR_RW (SFR5_BASE + 0x1a*4)
//#define CVSDDMAEWADR         SFR_RW (SFR5_BASE + 0x1b*4)
//#define CVSDDMADRADR         SFR_RW (SFR5_BASE + 0x1c*4)
//#define CVSDDMADWADR         SFR_RW (SFR5_BASE + 0x1d*4)
//#define CVSDPRED             SFR_RW (SFR5_BASE + 0x1e*4)
//#define CVSDPREACC           SFR_RW (SFR5_BASE + 0x1f*4)
#define SADCDAT0             SFR_RW (SFR5_BASE + 0x20*4)
#define SADCDAT1             SFR_RW (SFR5_BASE + 0x21*4)
#define SADCDAT2             SFR_RW (SFR5_BASE + 0x22*4)
#define SADCDAT3             SFR_RW (SFR5_BASE + 0x23*4)
#define SADCDAT4             SFR_RW (SFR5_BASE + 0x24*4)
#define SADCDAT5             SFR_RW (SFR5_BASE + 0x25*4)
#define SADCDAT6             SFR_RW (SFR5_BASE + 0x26*4)
#define SADCDAT7             SFR_RW (SFR5_BASE + 0x27*4)
#define SADCDAT8             SFR_RW (SFR5_BASE + 0x28*4)
#define SADCDAT9             SFR_RW (SFR5_BASE + 0x29*4)
#define SADCDAT10            SFR_RW (SFR5_BASE + 0x2a*4)
#define SADCDAT11            SFR_RW (SFR5_BASE + 0x2b*4)
#define SADCDAT12            SFR_RW (SFR5_BASE + 0x2c*4)
#define SADCDAT13            SFR_RW (SFR5_BASE + 0x2d*4)
#define SADCDAT14            SFR_RW (SFR5_BASE + 0x2e*4)
#define SADCDAT15            SFR_RW (SFR5_BASE + 0x2f*4)
#define SADCCON              SFR_RW (SFR5_BASE + 0x30*4)
#define SADCCH               SFR_RW (SFR5_BASE + 0x31*4)
#define SADCST               SFR_RW (SFR5_BASE + 0x32*4)
#define SADCBAUD             SFR_RW (SFR5_BASE + 0x33*4)
#define MBISTCON             SFR_RW (SFR5_BASE + 0x34*4)
#define MBISTEADR            SFR_RW (SFR5_BASE + 0x35*4)
#define MBISTBADR            SFR_RW (SFR5_BASE + 0x36*4)
#define MBISTCRC             SFR_RW (SFR5_BASE + 0x37*4)
#define MBISTERR             SFR_RW (SFR5_BASE + 0x38*4)
//efine GPDMACON             SFR_RW (SFR5_BASE + 0x39*4)
//efine GPDMAADDRST0         SFR_RW (SFR5_BASE + 0x3a*4)
//efine GPDMAADDRST1         SFR_RW (SFR5_BASE + 0x3b*4)
//efine GPDMAKICK            SFR_RW (SFR5_BASE + 0x3c*4)
#define EFCON0               SFR_RW (SFR5_BASE + 0x3d*4)
#define EFCON1               SFR_RW (SFR5_BASE + 0x3e*4)
#define EFDAT                SFR_RW (SFR5_BASE + 0x3f*4)

//------------------------- SFR Group6 ---------------------------------------//
#define GPIOASET        SFR_RW (SFR6_BASE + 0x00*4)
#define GPIOACLR        SFR_RW (SFR6_BASE + 0x01*4)
#define GPIOA           SFR_RW (SFR6_BASE + 0x02*4)
#define GPIOADIR        SFR_RW (SFR6_BASE + 0x03*4)
#define GPIOADE         SFR_RW (SFR6_BASE + 0x04*4)
#define GPIOAFEN        SFR_RW (SFR6_BASE + 0x05*4)
#define GPIOADRV        SFR_RW (SFR6_BASE + 0x06*4)
#define GPIOAPU         SFR_RW (SFR6_BASE + 0x07*4)
#define GPIOAPD         SFR_RW (SFR6_BASE + 0x08*4)
#define GPIOAPU200K     SFR_RW (SFR6_BASE + 0x09*4)
#define GPIOAPD200K     SFR_RW (SFR6_BASE + 0x0a*4)
#define GPIOAPU300      SFR_RW (SFR6_BASE + 0x0b*4)
#define GPIOAPD300      SFR_RW (SFR6_BASE + 0x0c*4)

#define GPIOBSET        SFR_RW (SFR6_BASE + 0x10*4)
#define GPIOBCLR        SFR_RW (SFR6_BASE + 0x11*4)
#define GPIOB           SFR_RW (SFR6_BASE + 0x12*4)
#define GPIOBDIR        SFR_RW (SFR6_BASE + 0x13*4)
#define GPIOBDE         SFR_RW (SFR6_BASE + 0x14*4)
#define GPIOBFEN        SFR_RW (SFR6_BASE + 0x15*4)
#define GPIOBDRV        SFR_RW (SFR6_BASE + 0x16*4)
#define GPIOBPU         SFR_RW (SFR6_BASE + 0x17*4)
#define GPIOBPD         SFR_RW (SFR6_BASE + 0x18*4)
#define GPIOBPU200K     SFR_RW (SFR6_BASE + 0x19*4)
#define GPIOBPD200K     SFR_RW (SFR6_BASE + 0x1a*4)
#define GPIOBPU300      SFR_RW (SFR6_BASE + 0x1b*4)
#define GPIOBPD300      SFR_RW (SFR6_BASE + 0x1c*4)

#define GPIOESET        SFR_RW (SFR6_BASE + 0x20*4)
#define GPIOECLR        SFR_RW (SFR6_BASE + 0x21*4)
#define GPIOE           SFR_RW (SFR6_BASE + 0x22*4)
#define GPIOEDIR        SFR_RW (SFR6_BASE + 0x23*4)
#define GPIOEDE         SFR_RW (SFR6_BASE + 0x24*4)
#define GPIOEFEN        SFR_RW (SFR6_BASE + 0x25*4)
#define GPIOEDRV        SFR_RW (SFR6_BASE + 0x26*4)
#define GPIOEPU         SFR_RW (SFR6_BASE + 0x27*4)
#define GPIOEPD         SFR_RW (SFR6_BASE + 0x28*4)
#define GPIOEPU200K     SFR_RW (SFR6_BASE + 0x29*4)
#define GPIOEPD200K     SFR_RW (SFR6_BASE + 0x2a*4)
#define GPIOEPU300      SFR_RW (SFR6_BASE + 0x2b*4)
#define GPIOEPD300      SFR_RW (SFR6_BASE + 0x2c*4)

#define GPIOFSET        SFR_RW (SFR6_BASE + 0x30*4)
#define GPIOFCLR        SFR_RW (SFR6_BASE + 0x31*4)
#define GPIOF           SFR_RW (SFR6_BASE + 0x32*4)
#define GPIOFDIR        SFR_RW (SFR6_BASE + 0x33*4)
#define GPIOFDE         SFR_RW (SFR6_BASE + 0x34*4)
#define GPIOFFEN        SFR_RW (SFR6_BASE + 0x35*4)
#define GPIOFDRV        SFR_RW (SFR6_BASE + 0x36*4)
#define GPIOFPU         SFR_RW (SFR6_BASE + 0x37*4)
#define GPIOFPD         SFR_RW (SFR6_BASE + 0x38*4)
#define GPIOFPU200K     SFR_RW (SFR6_BASE + 0x39*4)
#define GPIOFPD200K     SFR_RW (SFR6_BASE + 0x3a*4)
#define GPIOFPU300      SFR_RW (SFR6_BASE + 0x3b*4)
#define GPIOFPD300      SFR_RW (SFR6_BASE + 0x3c*4)

//------------------------- SFR Group7 ---------------------------------------//
#define GPIOGSET        SFR_RW (SFR7_BASE + 0x00*4)
#define GPIOGCLR        SFR_RW (SFR7_BASE + 0x01*4)
#define GPIOG           SFR_RW (SFR7_BASE + 0x02*4)
#define GPIOGDIR        SFR_RW (SFR7_BASE + 0x03*4)
#define GPIOGDE         SFR_RW (SFR7_BASE + 0x04*4)
#define GPIOGFEN        SFR_RW (SFR7_BASE + 0x05*4)
#define GPIOGDRV        SFR_RW (SFR7_BASE + 0x06*4)
#define GPIOGPU         SFR_RW (SFR7_BASE + 0x07*4)
#define GPIOGPD         SFR_RW (SFR7_BASE + 0x08*4)
#define GPIOGPU200K     SFR_RW (SFR7_BASE + 0x09*4)
#define GPIOGPD200K     SFR_RW (SFR7_BASE + 0x0a*4)
#define GPIOGPU300      SFR_RW (SFR7_BASE + 0x0b*4)
#define GPIOGPD300      SFR_RW (SFR7_BASE + 0x0c*4)

//------------------------- SFR Group8 ---------------------------------------//
#define UFADDR          SFR_RW (SFR8_BASE + 0x00*4)
#define UPOWER          SFR_RW (SFR8_BASE + 0x01*4)
#define UINTRTX1        SFR_RW (SFR8_BASE + 0x02*4)
#define UINTRTX2        SFR_RW (SFR8_BASE + 0x03*4)
#define UINTRRX1        SFR_RW (SFR8_BASE + 0x04*4)
#define UINTRRX2        SFR_RW (SFR8_BASE + 0x05*4)
#define UINTRUSB        SFR_RW (SFR8_BASE + 0x06*4)
#define UINTRTX1E       SFR_RW (SFR8_BASE + 0x07*4)
#define UINTRTX2E       SFR_RW (SFR8_BASE + 0x08*4)
#define UINTRRX1E       SFR_RW (SFR8_BASE + 0x09*4)
#define UINTRRX2E       SFR_RW (SFR8_BASE + 0x0a*4)
#define UINTRUSBE       SFR_RW (SFR8_BASE + 0x0b*4)
#define UFRAME1         SFR_RW (SFR8_BASE + 0x0c*4)
#define UFRAME2         SFR_RW (SFR8_BASE + 0x0d*4)
#define UINDEX          SFR_RW (SFR8_BASE + 0x0e*4)
#define UDEVCTL         SFR_RW (SFR8_BASE + 0x0f*4)

#define UTXMAXP         SFR_RW (SFR8_BASE + 0x10*4)
#define UCSR0           SFR_RW (SFR8_BASE + 0x11*4)
#define UTXCSR1         SFR_RW (SFR8_BASE + 0x11*4)
#define UTXCSR2         SFR_RW (SFR8_BASE + 0x12*4)
#define URXMAXP         SFR_RW (SFR8_BASE + 0x13*4)
#define URXCSR1         SFR_RW (SFR8_BASE + 0x14*4)
#define URXCSR2         SFR_RW (SFR8_BASE + 0x15*4)
#define UCOUNT0         SFR_RW (SFR8_BASE + 0x16*4)
#define URXCOUNT1       SFR_RW (SFR8_BASE + 0x16*4)
#define URXCOUNT2       SFR_RW (SFR8_BASE + 0x17*4)
#define UTXTYPE         SFR_RW (SFR8_BASE + 0x18*4)
#define UTXINTERVAL     SFR_RW (SFR8_BASE + 0x19*4)
#define URXTYPE         SFR_RW (SFR8_BASE + 0x1a*4)
#define URXINTERVAL     SFR_RW (SFR8_BASE + 0x1b*4)

#define UFIFO0          SFR_RW (SFR8_BASE + 0x20*4)
#define UFIFO1          SFR_RW (SFR8_BASE + 0x21*4)
#define UFIFO2          SFR_RW (SFR8_BASE + 0x22*4)
#define UFIFO3          SFR_RW (SFR8_BASE + 0x23*4)
#define UFIFO4          SFR_RW (SFR8_BASE + 0x24*4)
#define UFIFO5          SFR_RW (SFR8_BASE + 0x25*4)
#define UFIFO6          SFR_RW (SFR8_BASE + 0x26*4)
#define UFIFO7          SFR_RW (SFR8_BASE + 0x27*4)
#define UFIFO8          SFR_RW (SFR8_BASE + 0x28*4)
#define UFIFO9          SFR_RW (SFR8_BASE + 0x29*4)
#define UFIFO10         SFR_RW (SFR8_BASE + 0x2a*4)
#define UFIFO11         SFR_RW (SFR8_BASE + 0x2b*4)
#define UFIFO12         SFR_RW (SFR8_BASE + 0x2c*4)
#define UFIFO13         SFR_RW (SFR8_BASE + 0x2d*4)
#define UFIFO14         SFR_RW (SFR8_BASE + 0x2e*4)
#define UFIFO15         SFR_RW (SFR8_BASE + 0x2f*4)


//------------------------- SFR Group9 ---------------------------------------//
#define IRRXCON              SFR_RW (SFR9_BASE + 0x00*4)
#define IRRXDAT              SFR_RW (SFR9_BASE + 0x01*4)
#define IRRXCPND             SFR_RW (SFR9_BASE + 0x02*4)
#define IRRXERR0             SFR_RW (SFR9_BASE + 0x03*4)
#define IRRXERR1             SFR_RW (SFR9_BASE + 0x04*4)
#define IRRXPR0              SFR_RW (SFR9_BASE + 0x05*4)
#define IRRXPR1              SFR_RW (SFR9_BASE + 0x06*4)
//efine                      SFR_RW (SFR9_BASE + 0x07*4)
//efine                      SFR_RW (SFR9_BASE + 0x08*4)
//efine                      SFR_RW (SFR9_BASE + 0x09*4)
//efine                      SFR_RW (SFR9_BASE + 0x0a*4)
//efine                      SFR_RW (SFR9_BASE + 0x0b*4)
//efine                      SFR_RW (SFR9_BASE + 0x0c*4)
//efine                      SFR_RW (SFR9_BASE + 0x0d*4)
//efine                      SFR_RW (SFR9_BASE + 0x0e*4)
//efine                      SFR_RW (SFR9_BASE + 0x0f*4)
//efine GPDMACON0            SFR_RW (SFR9_BASE + 0x10*4)
//efine GPDMACON1            SFR_RW (SFR9_BASE + 0x11*4)
//efine GPDMASIZE            SFR_RW (SFR9_BASE + 0x12*4)
//efine GPDMAADRIN           SFR_RW (SFR9_BASE + 0x13*4)
//efine GPDMAADROUT          SFR_RW (SFR9_BASE + 0x14*4)
#define SQRT64L              SFR_RW (SFR9_BASE + 0x15*4)
#define SQRT64H              SFR_RW (SFR9_BASE + 0x16*4)
#define AUCON0               SFR_RW (SFR9_BASE + 0x17*4)
#define AUCON1               SFR_RW (SFR9_BASE + 0x18*4)
#define AUCON2               SFR_RW (SFR9_BASE + 0x19*4)
#define AUCON3               SFR_RW (SFR9_BASE + 0x1a*4)
#define AUCON4               SFR_RW (SFR9_BASE + 0x1b*4)
#define AUDMAADR             SFR_RW (SFR9_BASE + 0x1c*4)
//#define SBCECDMACNT          SFR_RW (SFR9_BASE + 0x1d*4)
//#define SBCECCON0            SFR_RW (SFR9_BASE + 0x1e*4)
//#define SBCECCON1            SFR_RW (SFR9_BASE + 0x1f*4)
//#define SBCECDMAINADR        SFR_RW (SFR9_BASE + 0x20*4)
//#define SBCECDMAOUTADR       SFR_RW (SFR9_BASE + 0x21*4)
#define BSPCON0              SFR_RW (SFR9_BASE + 0x22*4)
#define BSPBLNG              SFR_RW (SFR9_BASE + 0x23*4)
#define BSPDECCNT            SFR_RW (SFR9_BASE + 0x24*4)
#define BSPBUF               SFR_RW (SFR9_BASE + 0x25*4)
#define BSPBADR              SFR_RW (SFR9_BASE + 0x26*4)
#define PLCCON0              SFR_RW (SFR9_BASE + 0x27*4)
#define PLCCON1              SFR_RW (SFR9_BASE + 0x28*4)
#define PLCCON2              SFR_RW (SFR9_BASE + 0x29*4)
#define MINPOWER             SFR_RW (SFR9_BASE + 0x2a*4)
#define PLCKICK              SFR_RW (SFR9_BASE + 0x2b*4)
#define PLCLOOPBASE          SFR_RW (SFR9_BASE + 0x2c*4)
#define PLCLOOPSIZE          SFR_RW (SFR9_BASE + 0x2d*4)
#define PLCSPTR              SFR_RW (SFR9_BASE + 0x2e*4)
#define PLCOPTR              SFR_RW (SFR9_BASE + 0x2f*4)
#define PLCFADDR             SFR_RW (SFR9_BASE + 0x30*4)
#define SRC0CON              SFR_RW (SFR9_BASE + 0x31*4)
#define SRC0PHASECOMP        SFR_RW (SFR9_BASE + 0x32*4)
#define SRC0KICK             SFR_RW (SFR9_BASE + 0x33*4)
#define SRC0INADDR           SFR_RW (SFR9_BASE + 0x34*4)
#define SRC0OUTADDR          SFR_RW (SFR9_BASE + 0x35*4)
#define SRC0DMASIZE          SFR_RW (SFR9_BASE + 0x36*4)
#define SRC0DMACNT           SFR_RW (SFR9_BASE + 0x37*4)
#define SRC1CON              SFR_RW (SFR9_BASE + 0x38*4)
#define SRC1PHASECOMP        SFR_RW (SFR9_BASE + 0x39*4)
#define SRC1KICK             SFR_RW (SFR9_BASE + 0x3a*4)
#define SRC1INADDR           SFR_RW (SFR9_BASE + 0x3b*4)
#define SRC1OUTADDR          SFR_RW (SFR9_BASE + 0x3c*4)
#define SRC1DMASIZE          SFR_RW (SFR9_BASE + 0x3d*4)
#define SRC1DMACNT           SFR_RW (SFR9_BASE + 0x3e*4)
//#define SRC2DMASIZE          SFR_RW (SFR9_BASE + 0x3f*4)

//------------------------- SFR Group10 ---------------------------------------//
#define SWSINPHASE           SFR_RW (SFR10_BASE + 0x1e*4)
#define SWSINWAVE            SFR_RW (SFR10_BASE + 0x1f*4)
#define PIANOCON             SFR_RW (SFR10_BASE + 0x20*4)
#define PIANOBUF             SFR_RW (SFR10_BASE + 0x21*4)
#define TONEDLY              SFR_RW (SFR10_BASE + 0x22*4)
#define TONEDLY1             SFR_RW (SFR10_BASE + 0x23*4)

#define RDFTKICK             SFR_RW (SFR10_BASE + 0x2d*4)
#define RDFTCON              SFR_RW (SFR10_BASE + 0x2e*4)
#define RDFTIBADR            SFR_RW (SFR10_BASE + 0x2f*4)
#define RDFTOBADR            SFR_RW (SFR10_BASE + 0x30*4)
#define RDFTLBADR            SFR_RW (SFR10_BASE + 0x31*4)
#define TKCON                SFR_RW (SFR10_BASE + 0x32*4)
#define TKTMR                SFR_RW (SFR10_BASE + 0x33*4)
#define TKCH                 SFR_RW (SFR10_BASE + 0x34*4)
#define TKDMABADR            SFR_RW (SFR10_BASE + 0x35*4)
#define TKDMACNT             SFR_RW (SFR10_BASE + 0x36*4)
//PACC
#define PACC0CON0           SFR_RW (SFR10_BASE + 0x37*4)
#define PACC0CON1           SFR_RW (SFR10_BASE + 0x38*4)
#define PACC0CSADR          SFR_RW (SFR10_BASE + 0x39*4)
#define PACC0CSPTR          SFR_RO (SFR10_BASE + 0x3a*4)

//PACC1
#define PACC1CON0           SFR_RW (SFR10_BASE + 0x3b*4)
#define PACC1CON1           SFR_RW (SFR10_BASE + 0x3c*4)
#define PACC1CSADR          SFR_RW (SFR10_BASE + 0x3d*4)
#define PACC1CSPTR          SFR_RO (SFR10_BASE + 0x3e*4)


//efine                      SFR_RW (SFR10_BASE + 0x37*4)
//efine                      SFR_RW (SFR10_BASE + 0x38*4)
//efine                      SFR_RW (SFR10_BASE + 0x39*4)
//efine                      SFR_RW (SFR10_BASE + 0x3a*4)
//efine                      SFR_RW (SFR10_BASE + 0x3b*4)
//efine                      SFR_RW (SFR10_BASE + 0x3c*4)
//efine                      SFR_RW (SFR10_BASE + 0x3d*4)
//efine                      SFR_RW (SFR10_BASE + 0x3e*4)
//efine                      SFR_RW (SFR10_BASE + 0x3f*4)

//------------------------- SFR Group11 ---------------------------------------//
#define RTCCON0              SFR_RW (SFR11_BASE + 0x00*4)
#define RTCCON1              SFR_RW (SFR11_BASE + 0x01*4)
#define RTCCON2              SFR_RW (SFR11_BASE + 0x02*4)
#define RTCCON3              SFR_RW (SFR11_BASE + 0x03*4)
#define RTCCON4              SFR_RW (SFR11_BASE + 0x04*4)
#define RTCCON5              SFR_RW (SFR11_BASE + 0x05*4)
#define RTCCON6              SFR_RW (SFR11_BASE + 0x06*4)
#define RTCCON7              SFR_RW (SFR11_BASE + 0x07*4)
#define RTCCON8              SFR_RW (SFR11_BASE + 0x08*4)
#define RTCCON9              SFR_RW (SFR11_BASE + 0x09*4)
#define RTCCON10             SFR_RW (SFR11_BASE + 0x0a*4)
#define RTCCON11             SFR_RW (SFR11_BASE + 0x0b*4)
#define RTCCON12             SFR_RW (SFR11_BASE + 0x0c*4)
#define RTCCON13             SFR_RW (SFR11_BASE + 0x0d*4)
#define RTCCON14             SFR_RW (SFR11_BASE + 0x0e*4)
#define RTCCON15             SFR_RW (SFR11_BASE + 0x0f*4)
#define RTCRAMADR            SFR_RW (SFR11_BASE + 0x10*4)
#define RTCRAMDAT            SFR_RW (SFR11_BASE + 0x11*4)
#define RTCALM               SFR_RW (SFR11_BASE + 0x12*4)
#define RTCCNT               SFR_RW (SFR11_BASE + 0x13*4)
//efine                      SFR_RW (SFR11_BASE + 0x14*4)
//efine                      SFR_RW (SFR11_BASE + 0x15*4)
//efine                      SFR_RW (SFR11_BASE + 0x16*4)
//efine                      SFR_RW (SFR11_BASE + 0x17*4)
//efine                      SFR_RW (SFR11_BASE + 0x18*4)
//efine                      SFR_RW (SFR11_BASE + 0x19*4)
//efine                      SFR_RW (SFR11_BASE + 0x1a*4)
//efine                      SFR_RW (SFR11_BASE + 0x1b*4)
//efine                      SFR_RW (SFR11_BASE + 0x1c*4)
//efine                      SFR_RW (SFR11_BASE + 0x1d*4)
//efine                      SFR_RW (SFR11_BASE + 0x1e*4)
//efine                      SFR_RW (SFR11_BASE + 0x1f*4)
//efine                      SFR_RW (SFR11_BASE + 0x20*4)
//efine                      SFR_RW (SFR11_BASE + 0x21*4)
//efine                      SFR_RW (SFR11_BASE + 0x22*4)
//efine                      SFR_RW (SFR11_BASE + 0x23*4)
//efine                      SFR_RW (SFR11_BASE + 0x24*4)
//efine                      SFR_RW (SFR11_BASE + 0x25*4)
//efine                      SFR_RW (SFR11_BASE + 0x26*4)
//efine                      SFR_RW (SFR11_BASE + 0x27*4)
//efine                      SFR_RW (SFR11_BASE + 0x28*4)
//efine                      SFR_RW (SFR11_BASE + 0x29*4)
//efine                      SFR_RW (SFR11_BASE + 0x2a*4)
//efine                      SFR_RW (SFR11_BASE + 0x2b*4)
//efine                      SFR_RW (SFR11_BASE + 0x2c*4)
//efine                      SFR_RW (SFR11_BASE + 0x2d*4)
//efine                      SFR_RW (SFR11_BASE + 0x2e*4)
//efine                      SFR_RW (SFR11_BASE + 0x2f*4)
//efine                      SFR_RW (SFR11_BASE + 0x30*4)
//efine                      SFR_RW (SFR11_BASE + 0x31*4)
//efine                      SFR_RW (SFR11_BASE + 0x32*4)
//efine                      SFR_RW (SFR11_BASE + 0x33*4)
//efine                      SFR_RW (SFR11_BASE + 0x34*4)
//efine                      SFR_RW (SFR11_BASE + 0x35*4)
//efine                      SFR_RW (SFR11_BASE + 0x36*4)
//efine                      SFR_RW (SFR11_BASE + 0x37*4)
//efine                      SFR_RW (SFR11_BASE + 0x38*4)
//efine                      SFR_RW (SFR11_BASE + 0x39*4)
//efine                      SFR_RW (SFR11_BASE + 0x3a*4)
//efine                      SFR_RW (SFR11_BASE + 0x3b*4)
//efine                      SFR_RW (SFR11_BASE + 0x3c*4)
//efine                      SFR_RW (SFR11_BASE + 0x3d*4)
//efine                      SFR_RW (SFR11_BASE + 0x3e*4)
//efine                      SFR_RW (SFR11_BASE + 0x3f*4)

//------------------------- SFR Group12 ---------------------------------------//
#define AUBUF0CON            SFR_RW (SFR12_BASE + 0x00*4)
#define AUBUF0DATA           SFR_RW (SFR12_BASE + 0x01*4)
#define AUBUF0STARTADDR      SFR_RW (SFR12_BASE + 0x02*4)
#define AUBUF0SIZE           SFR_RW (SFR12_BASE + 0x03*4)
#define AUBUF0FIFOCNT        SFR_RW (SFR12_BASE + 0x04*4)
#define AUBUF0PTR            SFR_RW (SFR12_BASE + 0x05*4)
#define AUBUF0BACKUP         SFR_RW (SFR12_BASE + 0x06*4)
//efine AUBUF0DATA24R        SFR_RW (SFR12_BASE + 0x07*4)
#define AU0PEAKLEFT          SFR_RW (SFR12_BASE + 0x08*4)
//efine                      SFR_RW (SFR12_BASE + 0x09*4)
#define AU0PEAKRIGHT         SFR_RW (SFR12_BASE + 0x0a*4)
//efine                      SFR_RW (SFR12_BASE + 0x0b*4)
#define AUBUF0DMACON         SFR_RW (SFR12_BASE + 0x0c*4)
#define AUBUF0DMAADR         SFR_RW (SFR12_BASE + 0x0d*4)
#define AUBUF0DMAKICK        SFR_RW (SFR12_BASE + 0x0e*4)
#define AUBUF1CON            SFR_RW (SFR12_BASE + 0x0f*4)
#define AUBUF1DATA           SFR_RW (SFR12_BASE + 0x10*4)
#define AUBUF1STARTADDR      SFR_RW (SFR12_BASE + 0x11*4)
#define AUBUF1SIZE           SFR_RW (SFR12_BASE + 0x12*4)
#define AUBUF1FIFOCNT        SFR_RW (SFR12_BASE + 0x13*4)
#define AUBUF1PTR            SFR_RW (SFR12_BASE + 0x14*4)
//efine AUBUF1DATA24R        SFR_RW (SFR12_BASE + 0x15*4)
#define AUBUF1DMACON         SFR_RW (SFR12_BASE + 0x16*4)
#define AUBUF1DMAADR         SFR_RW (SFR12_BASE + 0x17*4)
#define AUBUF1DMAKICK        SFR_RW (SFR12_BASE + 0x18*4)
#define AUBUF2CON            SFR_RW (SFR12_BASE + 0x19*4)
#define AUBUF2DATA           SFR_RW (SFR12_BASE + 0x1a*4)
#define AUBUF2STARTADDR      SFR_RW (SFR12_BASE + 0x1b*4)
#define AUBUF2SIZE           SFR_RW (SFR12_BASE + 0x1c*4)
#define AUBUF2FIFOCNT        SFR_RW (SFR12_BASE + 0x1d*4)
#define AUBUF2PTR            SFR_RW (SFR12_BASE + 0x1e*4)
//efine AUBUF2DATA24R        SFR_RW (SFR12_BASE + 0x1f*4)
#define AUBUF2DMACON         SFR_RW (SFR12_BASE + 0x20*4)
#define AUBUF2DMAADR         SFR_RW (SFR12_BASE + 0x21*4)
#define AUBUF2DMAKICK        SFR_RW (SFR12_BASE + 0x22*4)
//efine                      SFR_RW (SFR12_BASE + 0x23*4)
//efine                      SFR_RW (SFR12_BASE + 0x24*4)
//efine                      SFR_RW (SFR12_BASE + 0x25*4)
#define AUANGCON0            SFR_RW (SFR12_BASE + 0x26*4)
#define AUANGCON1            SFR_RW (SFR12_BASE + 0x27*4)
#define AUANGCON2            SFR_RW (SFR12_BASE + 0x28*4)
#define AUANGCON3            SFR_RW (SFR12_BASE + 0x29*4)
#define AUANGCON4            SFR_RW (SFR12_BASE + 0x2a*4)
#define AUANGCON5            SFR_RW (SFR12_BASE + 0x2b*4)
#define AUANGCON6            SFR_RW (SFR12_BASE + 0x2c*4)
#define AUANGCON7            SFR_RW (SFR12_BASE + 0x2d*4)
//#define AUANGCON8            SFR_RW (SFR12_BASE + 0x2e*4)
//#define AUANGCON9            SFR_RW (SFR12_BASE + 0x2f*4)
//#define AUANGCON10           SFR_RW (SFR12_BASE + 0x30*4)
//#define AUANGCON11           SFR_RW (SFR12_BASE + 0x31*4)
//#define AUANGCON12           SFR_RW (SFR12_BASE + 0x32*4)
//#define AUANGCON13           SFR_RW (SFR12_BASE + 0x33*4)
//#define AUANGCON14           SFR_RW (SFR12_BASE + 0x34*4)
//#define AUANGCON15           SFR_RW (SFR12_BASE + 0x35*4)
//#define AUANGCON16           SFR_RW (SFR12_BASE + 0x36*4)
//#define AUANGCON17           SFR_RW (SFR12_BASE + 0x37*4)
//#define AUANGCON18           SFR_RW (SFR12_BASE + 0x38*4)
//#define AUANGCON19           SFR_RW (SFR12_BASE + 0x39*4)
//#define AUANGCON20           SFR_RW (SFR12_BASE + 0x3a*4)
//#define AUANGCON21           SFR_RW (SFR12_BASE + 0x3b*4)
//#define AUANGCON22           SFR_RW (SFR12_BASE + 0x3c*4)
//#define AUANGCON23           SFR_RW (SFR12_BASE + 0x3d*4)
//efine                      SFR_RW (SFR12_BASE + 0x3e*4)
//efine                      SFR_RW (SFR12_BASE + 0x3f*4)

//------------------------- SFR Group13 ---------------------------------------//
#define DACDIGCON0           SFR_RW (SFR13_BASE + 0x00*4)
#define DACRAMTADDR          SFR_RW (SFR13_BASE + 0x01*4)
#define DACRAMTDATA          SFR_RW (SFR13_BASE + 0x02*4)
#define DACVOLCON            SFR_RW (SFR13_BASE + 0x03*4)
#define SRC0VOLCON           SFR_RW (SFR13_BASE + 0x04*4)
#define SRC1VOLCON           SFR_RW (SFR13_BASE + 0x05*4)
#define SRC2VOLCON           SFR_RW (SFR13_BASE + 0x06*4)
#define AU0LMIXCOEF          SFR_RW (SFR13_BASE + 0x07*4)
#define AU0RMIXCOEF          SFR_RW (SFR13_BASE + 0x08*4)
#define AU1LMIXCOEF          SFR_RW (SFR13_BASE + 0x09*4)
#define AU1RMIXCOEF          SFR_RW (SFR13_BASE + 0x0a*4)
#define AU2LMIXCOEF          SFR_RW (SFR13_BASE + 0x0b*4)
#define AU2RMIXCOEF          SFR_RW (SFR13_BASE + 0x0c*4)
#define DACPWRCON            SFR_RW (SFR13_BASE + 0x0d*4)
#define DCSMPSSEL            SFR_RW (SFR13_BASE + 0x0e*4)
#define DCEXPECT             SFR_RW (SFR13_BASE + 0x0f*4)
#define DACRMDC              SFR_RW (SFR13_BASE + 0x10*4)
#define DACVSUPDC            SFR_RW (SFR13_BASE + 0x11*4)
#define DACDBGCON            SFR_RW (SFR13_BASE + 0x12*4)
#define DACEXTCON            SFR_RW (SFR13_BASE + 0x13*4)
#define DACBQ0CON            SFR_RW (SFR13_BASE + 0x14*4)
#define DACBQ1CON            SFR_RW (SFR13_BASE + 0x15*4)
#define DACBQFADECON         SFR_RW (SFR13_BASE + 0x16*4)
#define DACBQPEND            SFR_RW (SFR13_BASE + 0x17*4)
#define DACBQCOEF            SFR_RW (SFR13_BASE + 0x18*4)
#define PHASECOMP0           SFR_RW (SFR13_BASE + 0x19*4)
#define PHASECOMP1           SFR_RW (SFR13_BASE + 0x1a*4)
#define PHASECOMP2           SFR_RW (SFR13_BASE + 0x1b*4)
#define AU0DMAOCON           SFR_RW (SFR13_BASE + 0x1c*4)
#define AU0DMAOADR           SFR_RW (SFR13_BASE + 0x1d*4)
#define AU0DMAOSIZE          SFR_RW (SFR13_BASE + 0x1e*4)
//efine                      SFR_RW (SFR13_BASE + 0x1f*4)
//efine                      SFR_RW (SFR13_BASE + 0x20*4)
//efine                      SFR_RW (SFR13_BASE + 0x21*4)
//efine                      SFR_RW (SFR13_BASE + 0x22*4)
//efine                      SFR_RW (SFR13_BASE + 0x23*4)
//efine                      SFR_RW (SFR13_BASE + 0x24*4)
//efine                      SFR_RW (SFR13_BASE + 0x25*4)
//efine                      SFR_RW (SFR13_BASE + 0x26*4)
//efine                      SFR_RW (SFR13_BASE + 0x27*4)
//efine                      SFR_RW (SFR13_BASE + 0x28*4)
//efine                      SFR_RW (SFR13_BASE + 0x29*4)
//efine                      SFR_RW (SFR13_BASE + 0x2a*4)
//efine                      SFR_RW (SFR13_BASE + 0x2b*4)
//efine                      SFR_RW (SFR13_BASE + 0x2c*4)
//efine                      SFR_RW (SFR13_BASE + 0x2d*4)
//efine                      SFR_RW (SFR13_BASE + 0x2e*4)
//efine                      SFR_RW (SFR13_BASE + 0x2f*4)
//efine                      SFR_RW (SFR13_BASE + 0x30*4)
//efine                      SFR_RW (SFR13_BASE + 0x31*4)
//efine                      SFR_RW (SFR13_BASE + 0x32*4)
//efine                      SFR_RW (SFR13_BASE + 0x33*4)
//efine                      SFR_RW (SFR13_BASE + 0x34*4)
//efine                      SFR_RW (SFR13_BASE + 0x35*4)
//efine                      SFR_RW (SFR13_BASE + 0x36*4)
//efine                      SFR_RW (SFR13_BASE + 0x37*4)
//efine                      SFR_RW (SFR13_BASE + 0x38*4)
//efine                      SFR_RW (SFR13_BASE + 0x39*4)
//efine                      SFR_RW (SFR13_BASE + 0x3a*4)
//efine                      SFR_RW (SFR13_BASE + 0x3b*4)
//efine                      SFR_RW (SFR13_BASE + 0x3c*4)
//efine                      SFR_RW (SFR13_BASE + 0x3d*4)
//efine                      SFR_RW (SFR13_BASE + 0x3e*4)
//efine                      SFR_RW (SFR13_BASE + 0x3f*4)

//------------------------- SFR Group14 ---------------------------------------//
#define SDADCDMACON          SFR_RW (SFR14_BASE + 0x00*4)
#define SDADCDMAFLAG         SFR_RW (SFR14_BASE + 0x01*4)
#define SDADCDMACLR          SFR_RW (SFR14_BASE + 0x02*4)
#define SDADC0DMACON         SFR_RW (SFR14_BASE + 0x03*4)
#define SDADC0DMAADDR        SFR_RW (SFR14_BASE + 0x04*4)
#define SDADC0DMASIZE        SFR_RW (SFR14_BASE + 0x05*4)
#define SDADCCON             SFR_RW (SFR14_BASE + 0x06*4)
#define SDADC0CON            SFR_RW (SFR14_BASE + 0x07*4)
#define SDADC0RMDCCON        SFR_RW (SFR14_BASE + 0x08*4)
#define SDADC0GAIN           SFR_RW (SFR14_BASE + 0x09*4)
#define ADCRAMTADDR          SFR_RW (SFR14_BASE + 0x0a*4)
#define ADCRAMTDATA          SFR_RW (SFR14_BASE + 0x0b*4)
//efine                      SFR_RW (SFR14_BASE + 0x0c*4)
//efine                      SFR_RW (SFR14_BASE + 0x0d*4)
//efine                      SFR_RW (SFR14_BASE + 0x0e*4)
//efine                      SFR_RW (SFR14_BASE + 0x0f*4)
//efine                      SFR_RW (SFR14_BASE + 0x10*4)
//efine                      SFR_RW (SFR14_BASE + 0x11*4)
//efine                      SFR_RW (SFR14_BASE + 0x12*4)
//efine                      SFR_RW (SFR14_BASE + 0x13*4)
//efine                      SFR_RW (SFR14_BASE + 0x14*4)
//efine                      SFR_RW (SFR14_BASE + 0x15*4)
//efine                      SFR_RW (SFR14_BASE + 0x16*4)
//efine                      SFR_RW (SFR14_BASE + 0x17*4)
//efine                      SFR_RW (SFR14_BASE + 0x18*4)
//efine                      SFR_RW (SFR14_BASE + 0x19*4)
//efine                      SFR_RW (SFR14_BASE + 0x1a*4)
//efine                      SFR_RW (SFR14_BASE + 0x1b*4)
//efine                      SFR_RW (SFR14_BASE + 0x1c*4)
//efine                      SFR_RW (SFR14_BASE + 0x1d*4)
//efine                      SFR_RW (SFR14_BASE + 0x1e*4)
//efine                      SFR_RW (SFR14_BASE + 0x1f*4)
//efine                      SFR_RW (SFR14_BASE + 0x20*4)
//efine                      SFR_RW (SFR14_BASE + 0x21*4)
//efine                      SFR_RW (SFR14_BASE + 0x22*4)
//efine                      SFR_RW (SFR14_BASE + 0x23*4)
//efine                      SFR_RW (SFR14_BASE + 0x24*4)
//efine                      SFR_RW (SFR14_BASE + 0x25*4)
//efine                      SFR_RW (SFR14_BASE + 0x26*4)
//efine                      SFR_RW (SFR14_BASE + 0x27*4)
//efine                      SFR_RW (SFR14_BASE + 0x28*4)
//efine                      SFR_RW (SFR14_BASE + 0x29*4)
//efine                      SFR_RW (SFR14_BASE + 0x2a*4)
//efine                      SFR_RW (SFR14_BASE + 0x2b*4)
//efine                      SFR_RW (SFR14_BASE + 0x2c*4)
//efine                      SFR_RW (SFR14_BASE + 0x2d*4)
//efine                      SFR_RW (SFR14_BASE + 0x2e*4)
//efine                      SFR_RW (SFR14_BASE + 0x2f*4)
//efine                      SFR_RW (SFR14_BASE + 0x30*4)
//efine                      SFR_RW (SFR14_BASE + 0x31*4)
//efine                      SFR_RW (SFR14_BASE + 0x32*4)
//efine                      SFR_RW (SFR14_BASE + 0x33*4)
//efine                      SFR_RW (SFR14_BASE + 0x34*4)
//efine                      SFR_RW (SFR14_BASE + 0x35*4)
//efine                      SFR_RW (SFR14_BASE + 0x36*4)
//efine                      SFR_RW (SFR14_BASE + 0x37*4)
//efine                      SFR_RW (SFR14_BASE + 0x38*4)
//efine                      SFR_RW (SFR14_BASE + 0x39*4)
//efine                      SFR_RW (SFR14_BASE + 0x3a*4)
//efine                      SFR_RW (SFR14_BASE + 0x3b*4)
//efine                      SFR_RW (SFR14_BASE + 0x3c*4)
//efine                      SFR_RW (SFR14_BASE + 0x3d*4)
//efine                      SFR_RW (SFR14_BASE + 0x3e*4)
//efine                      SFR_RW (SFR14_BASE + 0x3f*4)

//------------------------- SFR Group15 ---------------------------------------//
//efine                      SFR_RW (SFR15_BASE + 0x0f*4)
#define FMRXDGTCON0            SFR_RW (SFR15_BASE + 0x10*4)
#define FMRXKICK               SFR_RW (SFR15_BASE + 0x11*4)
#define FMRXFLAG               SFR_RW (SFR15_BASE + 0x12*4)
#define FMRXDCSUM              SFR_RW (SFR15_BASE + 0x13*4)
#define FMRXRSSISUM            SFR_RW (SFR15_BASE + 0x14*4)
#define FMRXRSSIPOW            SFR_RW (SFR15_BASE + 0x15*4)
#define FMRXPILOTPOW           SFR_RW (SFR15_BASE + 0x16*4)
#define FMRXBALANVOL           SFR_RW (SFR15_BASE + 0x17*4)
#define FMRXZEROCROSSCON       SFR_RW (SFR15_BASE + 0x18*4)
#define FMRXDAMADDR            SFR_RW (SFR15_BASE + 0x19*4)
#define FMRXDMASIZE            SFR_RW (SFR15_BASE + 0x1a*4)
#define FMRXDMACON             SFR_RW (SFR15_BASE + 0x1b*4)
#define FMRXDMAFLAG            SFR_RW (SFR15_BASE + 0x1c*4)
#define FMRXZEROCROSSCNT       SFR_RW (SFR15_BASE + 0x1d*4)
//efine                      SFR_RW (SFR15_BASE + 0x1e*4)
//efine                      SFR_RW (SFR15_BASE + 0x1f*4)
//efine                      SFR_RW (SFR15_BASE + 0x20*4)
//efine                      SFR_RW (SFR15_BASE + 0x21*4)
//efine                      SFR_RW (SFR15_BASE + 0x22*4)
//efine                      SFR_RW (SFR15_BASE + 0x23*4)
//efine                      SFR_RW (SFR15_BASE + 0x24*4)
//efine                      SFR_RW (SFR15_BASE + 0x25*4)
//efine                      SFR_RW (SFR15_BASE + 0x26*4)
//efine                      SFR_RW (SFR15_BASE + 0x27*4)
//efine                      SFR_RW (SFR15_BASE + 0x28*4)
//efine                      SFR_RW (SFR15_BASE + 0x29*4)
//efine                      SFR_RW (SFR15_BASE + 0x2a*4)
//efine                      SFR_RW (SFR15_BASE + 0x2b*4)
//efine                      SFR_RW (SFR15_BASE + 0x2c*4)
//efine                      SFR_RW (SFR15_BASE + 0x2d*4)
//efine                      SFR_RW (SFR15_BASE + 0x2e*4)
//efine                      SFR_RW (SFR15_BASE + 0x2f*4)
//efine                      SFR_RW (SFR15_BASE + 0x30*4)
//efine                      SFR_RW (SFR15_BASE + 0x31*4)
//efine                      SFR_RW (SFR15_BASE + 0x32*4)
//efine                      SFR_RW (SFR15_BASE + 0x33*4)
//efine                      SFR_RW (SFR15_BASE + 0x34*4)
//efine                      SFR_RW (SFR15_BASE + 0x35*4)
//efine                      SFR_RW (SFR15_BASE + 0x36*4)
//efine                      SFR_RW (SFR15_BASE + 0x37*4)
//efine                      SFR_RW (SFR15_BASE + 0x38*4)
//efine                      SFR_RW (SFR15_BASE + 0x39*4)
//efine                      SFR_RW (SFR15_BASE + 0x3a*4)
//efine                      SFR_RW (SFR15_BASE + 0x3b*4)
//efine                      SFR_RW (SFR15_BASE + 0x3c*4)
//efine                      SFR_RW (SFR15_BASE + 0x3d*4)
//efine                      SFR_RW (SFR15_BASE + 0x3e*4)
//efine                      SFR_RW (SFR15_BASE + 0x3f*4)

//------------------------- SFR Group16 ---------------------------------------//
//efine                      SFR_RW (SFR16_BASE + 0x00*4)

//------------------------- SFR Group17 ---------------------------------------//
//0~35 used for ANC

//------------------------- SFR Group30 ---------------------------------------//
#define FPGADBGCLR           SFR_RW (SFR30_BASE + 0x00*4)
#define FPGADBGSET           SFR_RW (SFR30_BASE + 0x01*4)
#define FPGAUTCON            SFR_RW (SFR30_BASE + 0x02*4)
#define FPGAUTDATA           SFR_RW (SFR30_BASE + 0x03*4)
#define FPGAUTCPND           SFR_RW (SFR30_BASE + 0x04*4)
#define FPGAUTBAUD           SFR_RW (SFR30_BASE + 0x05*4)
#define FPGATEST             SFR_RW (SFR30_BASE + 0x06*4)
//efine                      SFR_RW (SFR30_BASE + 0x07*4)
#define FPGAUTCON2           SFR_RW (SFR30_BASE + 0x08*4)
#define FPGAUTDAT2           SFR_RW (SFR30_BASE + 0x09*4)
#define FPGAUTCPND2          SFR_RW (SFR30_BASE + 0x0a*4)
#define FPGAUTBAUD2          SFR_RW (SFR30_BASE + 0x0b*4)

#define FPGAUTCON1           SFR_RW (SFR30_BASE + 0x0c*4)
#define FPGAUTDAT1           SFR_RW (SFR30_BASE + 0x0d*4)
#define FPGAUTCPND1          SFR_RW (SFR30_BASE + 0x0e*4)
#define FPGAUTBAUD1          SFR_RW (SFR30_BASE + 0x0f*4)

#endif
